return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "lemminx",
      "bash-language-server",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "hadolint",
      "java-debug-adapter",
      "java-test",
      "lua-language-server",
      "prettier",
      "shellcheck",
      "shfmt",
      "sonarlint-language-server",
      "sqlfluff",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "vtsls",
      "yaml-language-server",
    },
  },
}
