return {
  "mason-org/mason.nvim",
  opts = {
    ui = {
      icons = {
        package_installed = "✓",
        package_pending = "➜",
        package_uninstalled = "✗",
      },
    },
    ensure_installed = {
      "lemminx",
      "bash-language-server",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "hadolint",
      "java-debug-adapter",
      "java-test",
      "lua-language-server",
      "prettier",
      "shellcheck",
      "shfmt",
      "sonarlint-language-server",
      "sqlfluff",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "vtsls",
      "yaml-language-server",
      "llm-ls",
      "ktlint",
      "apex-language-server",
      "lwc-language-server",
      "visualforce-language-server",
      "vim-language-server",
    },
  },
}
