#!/usr/bin/env zsh

FONT_FACE="Maple Mono NF"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
MEDIUM_FONT_SIZE=12.0
LARGE_FONT_SIZE=15.0

sketchybar --bar \
    height=38 \
    color=0x66494d64 \
    margin=0 \
    sticky=on \
    padding_left=23 \
    padding_right=23 \
    notch_width=188 \
    display=main

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a / 0x66494d64
sketchybar --default \
    background.color=0x9924273a \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:$LARGE_FONT_SIZE" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:$MEDIUM_FONT_SIZE" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5


# spacer específico para la zona derecha del notch
sketchybar --add item spotify_spacer e \
    --set spotify_spacer \
      width=28 \
      background.drawing=off \
      label.drawing=off \
      icon.drawing=off

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify e \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    icon.font="$FONT_FACE:Bold:20.0" \
    label.drawing=off \
    label.padding_left=5 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5a97f \
    icon.color=0xff24273a \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    icon.color=0xff24273a \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    background.padding_left=-3 \
    icon= \
    icon.color=0xffa6da95 \
    icon.font="$FONT_FACE:Bold:20.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=0 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:$MEDIUM_FONT_SIZE" \
    label.drawing=yes

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item spacer left \
           --set spacer width=15 \
           background.drawing=off

sketchybar --add event aerospace_workspace_change
monitors=$(aerospace list-monitors --format '%{monitor-id} %{monitor-appkit-nsscreen-screens-id}' | awk '{print $1 "=" $2}')
for monitor_pair in $monitors; do
  monitor_id=$(echo "$monitor_pair" | cut -d '=' -f 1)
  display_id=$(echo "$monitor_pair" | cut -d '=' -f 2)

  # for sid in $(aerospace list-workspaces --all); do
  for sid in $(aerospace list-workspaces --monitor $monitor_id); do
      sketchybar --add item space.$sid left \
          --subscribe space.$sid aerospace_workspace_change \
          --set space.$sid \
            display=${monitors["$monitor_id"]}\
            background.color=0x00000000 \
            background.corner_radius=5 \
            background.padding_right=0 \
            background.height=20 \
            icon.font="$FONT_FACE:Medium:$LARGE_FONT_SIZE" \
            icon.padding_left=0 \
            icon.padding_right=0 \
            label.font="$FONT_FACE:Medium:$MEDIUM_FONT_SIZE" \
            label.color=0xffcad3f5 \
            label.y_offset=0 \
            label.padding_left=3 \
            label.padding_right=3 \
            background.drawing=off \
          label="$sid" \
          click_script="aerospace workspace $sid" \
          script="$CONFIG_DIR/plugins/aerospace.sh $sid $MEDIUM_FONT_SIZE $LARGE_FONT_SIZE"
  done
done

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change

sketchybar --add item wifi right \
           --set wifi icon.drawing=on \
                    icon.color=0xffb7bdf8\
                    label.drawing=true \
                    label.padding_right=0 \
                    icon.padding_right=3 \
                    script="$PLUGIN_SHARED_DIR/wifi.sh" \
                    update_freq=10 

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
