local M = {}
local model = require("modules.editor.keymap_docs.model")
local view = require("modules.editor.keymap_docs.view")

local docs = {
  { mode = "n", keys = "<Leader>a", desc = "+AI" },
  { mode = "x", keys = "<Leader>a", desc = "+AI" },
  { mode = "n", keys = "<Leader>am", desc = "+Minuet/NES" },
  { mode = "n", keys = "<Leader>D", desc = "+Database" },
  { mode = "n", keys = "<Leader>b", desc = "+Buffers" },
  { mode = "n", keys = "<Leader>c", desc = "+Code" },
  { mode = "x", keys = "<Leader>c", desc = "+Code" },
  { mode = "n", keys = "<Leader>d", desc = "+Debug" },
  { mode = "x", keys = "<Leader>d", desc = "+Debug" },
  { mode = "n", keys = "<Leader>db", desc = "+Breakpoints" },
  { mode = "n", keys = "<Leader>e", desc = "File Explorer (cwd)" },
  { mode = "n", keys = "<Leader>E", desc = "File Explorer (root)" },
  { mode = "n", keys = "<F1>", desc = "Netrw: help", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "<CR>", desc = "Netrw: enter directory or open file", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "<Del>", desc = "Netrw: remove file or directory", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "<C-h>", desc = "Netrw: edit file hiding list", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "<C-r>", desc = "Netrw: browse using gvim server", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "<C-Tab>", desc = "Netrw: shrink or expand explore window", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "<Leader>eh", desc = "Netrw: edit file hiding list", group = "Netrw" },
  { mode = "n", keys = "<Leader>er", desc = "Netrw: refresh directory listing", group = "Netrw" },
  { mode = "n", keys = "-", desc = "Netrw: go up one directory", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "a", desc = "Netrw: cycle normal, hiding, and showing display", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "cd", desc = "Netrw: make browsing directory the current directory", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "C", desc = "Netrw: set editing window", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "d", desc = "Netrw: make directory", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "D", desc = "Netrw: remove file(s) or directory(ies)", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "gb", desc = "Netrw: go to previous bookmarked directory", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "gd", desc = "Netrw: force treatment as directory", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "gf", desc = "Netrw: force treatment as file", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "gh", desc = "Netrw: quick hide or unhide dot-files", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "gn", desc = "Netrw: make cursor directory top of tree", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "gp", desc = "Netrw: change local file permissions", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "i", desc = "Netrw: cycle thin, long, wide, and tree listings", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "I", desc = "Netrw: toggle banner", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mb", desc = "Netrw: bookmark current directory", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mc", desc = "Netrw: copy marked files to target", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "md", desc = "Netrw: apply diff to marked files", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "me", desc = "Netrw: edit marked files via arglist", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mf", desc = "Netrw: mark file", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mF", desc = "Netrw: unmark files", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mg", desc = "Netrw: vimgrep marked files", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mh", desc = "Netrw: toggle marked suffixes in hiding list", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mm", desc = "Netrw: move marked files to target", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mr", desc = "Netrw: mark files by shell-style regexp", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mt", desc = "Netrw: set current directory as markfile target", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mT", desc = "Netrw: apply ctags to marked files", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mu", desc = "Netrw: unmark all marked files", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mv", desc = "Netrw: apply Vim command to marked files", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mx", desc = "Netrw: apply shell command to marked files", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mX", desc = "Netrw: shell command marked files en bloc", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "mz", desc = "Netrw: compress or decompress marked files", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "o", desc = "Netrw: open in horizontal split browser", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "O", desc = "Netrw: obtain file under cursor", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "p", desc = "Netrw: preview file", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "P", desc = "Netrw: browse in previously used window", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "qb", desc = "Netrw: list bookmarks and history", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "qf", desc = "Netrw: display file information", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "qF", desc = "Netrw: mark files using quickfix list", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "qL", desc = "Netrw: mark files using location list", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "r", desc = "Netrw: reverse sorting order", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "R", desc = "Netrw: rename file(s) or directory(ies)", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "s", desc = "Netrw: select sort by name, time, or size", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "S", desc = "Netrw: specify suffix priority for name sort", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "t", desc = "Netrw: open in new tab", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "u", desc = "Netrw: change to recently visited directory", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "U", desc = "Netrw: change to subsequently visited directory", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "v", desc = "Netrw: open in vertical split browser", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "x", desc = "Netrw: view file with associated program", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "X", desc = "Netrw: execute filename under cursor", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "%", desc = "Netrw: open new file in current directory", source = "default-doc", group = "Netrw" },
  { mode = "n", keys = "<Leader>f", desc = "+Files/Terminal" },
  { mode = "n", keys = "<Leader>fc", desc = "Config files" },
  { mode = "n", keys = "<Leader>g", desc = "+Git" },
  { mode = "x", keys = "<Leader>g", desc = "+Git" },
  { mode = "n", keys = "<Leader>gb", desc = "Git blame line diff preview" },
  { mode = "n", keys = "<Leader>gd", desc = "Git diff current file" },
  { mode = "n", keys = "<Leader>gD", desc = "Git diff against HEAD~" },
  { mode = "n", keys = "<Leader>gf", desc = "Git file history diff preview" },
  { mode = "n", keys = "<Leader>gg", desc = "Lazygit cwd" },
  { mode = "n", keys = "<Leader>gG", desc = "Lazygit root" },
  { mode = "n", keys = "<Leader>gl", desc = "Git log diff preview cwd" },
  { mode = "n", keys = "<Leader>gL", desc = "Git log diff preview root" },
  { mode = "n", keys = "<Leader>gp", desc = "Git preview hunk" },
  { mode = "n", keys = "<Leader>gr", desc = "Git reset hunk" },
  { mode = "n", keys = "<Leader>gR", desc = "Git reset buffer" },
  { mode = "n", keys = "<Leader>gs", desc = "Git stage hunk" },
  { mode = "n", keys = "<Leader>gS", desc = "Git stage buffer" },
  { mode = "n", keys = "<Leader>gB", desc = "Git browse open" },
  { mode = "x", keys = "<Leader>gB", desc = "Git browse open" },
  { mode = "n", keys = "<Leader>gY", desc = "Git browse copy URL" },
  { mode = "x", keys = "<Leader>gY", desc = "Git browse copy URL" },
  { mode = "n", keys = "<Leader>J", desc = "+Java" },
  { mode = "x", keys = "<Leader>J", desc = "+Java" },
  { mode = "n", keys = "<Leader>Jd", desc = "+Decompiled Jars" },
  { mode = "n", keys = "<Leader>Jdb", desc = "Java decompiled buffers" },
  { mode = "n", keys = "<Leader>Jdd", desc = "Java decompile/go to definition" },
  { mode = "n", keys = "<Leader>Jdp", desc = "Java decompiled peek definition" },
  { mode = "n", keys = "<Leader>Jdy", desc = "Java decompiled copy URI" },
  { mode = "n", keys = "<Leader>Je", desc = "+Escape/Extract" },
  { mode = "x", keys = "<Leader>Je", desc = "+Escape/Extract" },
  { mode = "n", keys = "<Leader>Jt", desc = "+Tools/Spring" },
  { mode = "n", keys = "<Leader>p", desc = "+Project/Sessions" },
  { mode = "n", keys = "<Leader>q", desc = "+Quit" },
  { mode = "n", keys = "<Leader>r", desc = "+Refactor" },
  { mode = "x", keys = "<Leader>r", desc = "+Refactor" },
  { mode = "n", keys = "<Leader>s", desc = "+Search" },
  { mode = "x", keys = "<Leader>s", desc = "+Search" },
  { mode = "n", keys = "<Leader>t", desc = "+Tests" },
  { mode = "n", keys = "<Leader>tt", desc = "+Java/Maven tests" },
  { mode = "n", keys = "<Leader>td", desc = "+Java/Maven debug" },
  { mode = "n", keys = "<Leader>S", desc = "+Salesforce" },
  { mode = "n", keys = "<Leader>m", desc = "+MyBatis" },
  { mode = "n", keys = "<Leader>n", desc = "+No Neck Pain" },
  { mode = "n", keys = "<Leader>np", desc = "No Neck Pain: toggle" },
  { mode = "n", keys = "<Leader>n=", desc = "No Neck Pain: width up" },
  { mode = "n", keys = "<Leader>n-", desc = "No Neck Pain: width down" },
  { mode = "n", keys = "<Leader>nql", desc = "No Neck Pain: toggle left side" },
  { mode = "n", keys = "<Leader>nqr", desc = "No Neck Pain: toggle right side" },
  { mode = "n", keys = "<Leader>ns", desc = "No Neck Pain: scratch pad" },
  { mode = "n", keys = "<Leader>nd", desc = "No Neck Pain: debug" },
  { mode = "n", keys = "<Leader>u", desc = "+UI" },
  { mode = "n", keys = "<Leader>uC", desc = "Select colorscheme" },
  { mode = "n", keys = "<Leader>uV", desc = "Reload Neovim config" },
  { mode = "n", keys = "<Leader>w", desc = "+Windows" },
  { mode = "n", keys = "<Leader>x", desc = "+Lists" },
  { mode = "n", keys = "<Leader><Tab>", desc = "+Tabs" },
  { mode = "n", keys = "gc", desc = "+Comment" },
  { mode = "n", keys = "gp", desc = "+Quick Preview" },
  { mode = "n", keys = "gr", desc = "+LSP actions" },
  { mode = "x", keys = "gr", desc = "+LSP actions" },
  { mode = "n", keys = "s", desc = "+Surround/Flash" },
  { mode = "x", keys = "s", desc = "+Surround/Flash" },
  { mode = "o", keys = "s", desc = "+Surround/Flash" },

  { mode = "n", keys = "[X", desc = "Jump to context start" },
  { mode = "n", keys = "[h", desc = "Prev git hunk" },
  { mode = "n", keys = "]h", desc = "Next git hunk" },
  { mode = "n", keys = "[t", desc = "Prev TODO" },
  { mode = "n", keys = "]t", desc = "Next TODO" },
  { mode = "n", keys = "[d", desc = "Default: previous diagnostic", source = "default-doc" },
  { mode = "n", keys = "]d", desc = "Default: next diagnostic", source = "default-doc" },
  { mode = "n", keys = "[b", desc = "Default: previous buffer", source = "default-doc" },
  { mode = "n", keys = "]b", desc = "Default: next buffer", source = "default-doc" },
  { mode = "n", keys = "[q", desc = "Default: previous quickfix item", source = "default-doc" },
  { mode = "n", keys = "]q", desc = "Default: next quickfix item", source = "default-doc" },
  { mode = "n", keys = "[l", desc = "Default: previous location-list item", source = "default-doc" },
  { mode = "n", keys = "]l", desc = "Default: next location-list item", source = "default-doc" },
  { mode = "n", keys = "[f", desc = "Prev function start" },
  { mode = "n", keys = "]f", desc = "Next function start" },
  { mode = "n", keys = "[F", desc = "Prev function end" },
  { mode = "n", keys = "]F", desc = "Next function end" },
  { mode = "n", keys = "[c", desc = "Prev class/change" },
  { mode = "n", keys = "]c", desc = "Next class/change" },
  { mode = "n", keys = "[a", desc = "Prev parameter" },
  { mode = "n", keys = "]a", desc = "Next parameter" },
  { mode = "n", keys = "[[", desc = "Prev reference" },
  { mode = "n", keys = "]]", desc = "Next reference" },

  { mode = "n", keys = "gg", desc = "Go to first line" },
  { mode = "n", keys = "G", desc = "Go to last line" },
  { mode = "n", keys = "0", desc = "Go to first column" },
  { mode = "n", keys = "^", desc = "Go to first non-blank" },
  { mode = "n", keys = "$", desc = "Go to end of line" },
  { mode = "n", keys = "%", desc = "Jump matching pair" },
  { mode = "n", keys = "{", desc = "Previous paragraph/block" },
  { mode = "n", keys = "}", desc = "Next paragraph/block" },
  { mode = "n", keys = "zz", desc = "Center cursor line" },
  { mode = "n", keys = "zt", desc = "Cursor line to top" },
  { mode = "n", keys = "zb", desc = "Cursor line to bottom" },
  { mode = "n", keys = "<C-u>", desc = "Scroll half-page up" },
  { mode = "n", keys = "<C-d>", desc = "Scroll half-page down" },
  { mode = "n", keys = "<C-b>", desc = "Scroll page up" },
  { mode = "n", keys = "<C-f>", desc = "Scroll page down" },
  { mode = "n", keys = "*", desc = "Search word forward" },
  { mode = "n", keys = "#", desc = "Search word backward" },
  { mode = "n", keys = "n", desc = "Next search match" },
  { mode = "n", keys = "N", desc = "Previous search match" },
  { mode = "n", keys = "u", desc = "Undo" },
  { mode = "n", keys = "<C-r>", desc = "Redo" },
  { mode = "n", keys = ".", desc = "Repeat last change" },
  { mode = "n", keys = "q", desc = "Record macro" },
  { mode = "n", keys = "@", desc = "Replay macro" },
  { mode = "n", keys = "J", desc = "Join lines" },
  { mode = "n", keys = "~", desc = "Toggle case" },
  { mode = "n", keys = "=", desc = "Format operator" },
  { mode = "n", keys = "Y", desc = "Default: yank to end of line", source = "default-doc" },
  { mode = "n", keys = "Q", desc = "Default: replay register q", source = "default-doc" },
  { mode = "n", keys = "&", desc = "Default: repeat substitute with flags", source = "default-doc" },
  { mode = "x", keys = "&", desc = "Default: repeat substitute with flags", source = "default-doc" },
  { mode = "n", keys = "gx", desc = "Default: open file or URI under cursor", source = "default-doc" },
  { mode = "x", keys = "gx", desc = "Default: open selected file or URI", source = "default-doc" },
  { mode = "n", keys = "]<Space>", desc = "Default: add empty line below", source = "default-doc" },
  { mode = "n", keys = "[<Space>", desc = "Default: add empty line above", source = "default-doc" },
  { mode = "n", keys = "]d", desc = "Default: next diagnostic", source = "default-doc" },
  { mode = "n", keys = "[d", desc = "Default: previous diagnostic", source = "default-doc" },
  { mode = "n", keys = "]D", desc = "Default: last diagnostic", source = "default-doc" },
  { mode = "n", keys = "[D", desc = "Default: first diagnostic", source = "default-doc" },
  { mode = "n", keys = "]q", desc = "Default: next quickfix item", source = "default-doc" },
  { mode = "n", keys = "[q", desc = "Default: previous quickfix item", source = "default-doc" },
  { mode = "n", keys = "]Q", desc = "Default: last quickfix item", source = "default-doc" },
  { mode = "n", keys = "[Q", desc = "Default: first quickfix item", source = "default-doc" },
  { mode = "n", keys = "]l", desc = "Default: next location-list item", source = "default-doc" },
  { mode = "n", keys = "[l", desc = "Default: previous location-list item", source = "default-doc" },
  { mode = "n", keys = "]L", desc = "Default: last location-list item", source = "default-doc" },
  { mode = "n", keys = "[L", desc = "Default: first location-list item", source = "default-doc" },
  { mode = "n", keys = "]t", desc = "Default: next tag in tag stack", source = "default-doc" },
  { mode = "n", keys = "[t", desc = "Default: previous tag in tag stack", source = "default-doc" },
  { mode = "n", keys = "]T", desc = "Default: last tag in tag stack", source = "default-doc" },
  { mode = "n", keys = "[T", desc = "Default: first tag in tag stack", source = "default-doc" },
  { mode = "n", keys = "zf", desc = "Create fold" },
  { mode = "n", keys = "zo", desc = "Open fold" },
  { mode = "n", keys = "zc", desc = "Close fold" },
  { mode = "n", keys = "za", desc = "Toggle fold" },
  { mode = "n", keys = "zR", desc = "Open all folds" },
  { mode = "n", keys = "zM", desc = "Close all folds" },

  { mode = "n", keys = "do", desc = "Diff: obtain change" },
  { mode = "n", keys = "dp", desc = "Diff: put change" },
  { mode = "n", keys = "dO", desc = "Diff: obtain all local" },
  { mode = "n", keys = "dP", desc = "Diff: put all remote" },

  { mode = "n", keys = "gpd", desc = "Quick Preview: definition" },
  { mode = "n", keys = "gpt", desc = "Quick Preview: type definition" },
  { mode = "n", keys = "gpi", desc = "Quick Preview: implementation" },
  { mode = "n", keys = "gpD", desc = "Quick Preview: declaration" },
  { mode = "n", keys = "gpr", desc = "Quick Preview: references" },
  { mode = "n", keys = "gpc", desc = "Quick Preview: close all" },

  { mode = "n", keys = "gd", desc = "Go to definition" },
  { mode = "n", keys = "gD", desc = "Go to declaration" },
  { mode = "n", keys = "grt", desc = "Go to type definition" },
  { mode = "n", keys = "gV", desc = "Vsplit and go to definition" },
  { mode = "n", keys = "gra", desc = "Code action" },
  { mode = "x", keys = "gra", desc = "Code action" },
  { mode = "n", keys = "grn", desc = "Rename symbol" },
  { mode = "n", keys = "grr", desc = "References" },
  { mode = "n", keys = "gri", desc = "Go to implementation" },
  { mode = "n", keys = "gO", desc = "Document symbols" },
  { mode = "n", keys = "gW", desc = "Workspace symbols" },
  { mode = "n", keys = "gK", desc = "Signature help" },

  { mode = "n", keys = "gcc", desc = "Toggle line comment" },
  { mode = "x", keys = "gc", desc = "Toggle selection comment" },
  { mode = "n", keys = "gco", desc = "Add comment below" },
  { mode = "n", keys = "gcO", desc = "Add comment above" },

  { mode = "n", keys = "sa", desc = "Surround: add" },
  { mode = "x", keys = "sa", desc = "Surround: add selection" },
  { mode = "n", keys = "sd", desc = "Surround: delete" },
  { mode = "n", keys = "sr", desc = "Surround: replace" },
  { mode = "n", keys = "sf", desc = "Surround: find next" },
  { mode = "n", keys = "sF", desc = "Surround: find previous" },
  { mode = "n", keys = "sh", desc = "Surround: highlight" },
  { mode = "n", keys = "sn", desc = "Surround: update n_lines" },
  { mode = "n", keys = "ss", desc = "Flash jump" },
  { mode = "x", keys = "ss", desc = "Flash jump" },
  { mode = "o", keys = "ss", desc = "Flash jump" },
  { mode = "n", keys = "sS", desc = "Flash Treesitter" },
  { mode = "o", keys = "sS", desc = "Flash Treesitter" },
}

function M.items()
  return model.items(docs)
end

function M.select()
  view.select(M.items)
end

function M.open_docs()
  view.open_docs(M.items)
end

function M.setup()
  vim.api.nvim_create_user_command("Keymaps", M.select, { desc = "Select keymaps and documented key groups" })
  vim.api.nvim_create_user_command("KeymapDocs", M.open_docs, { desc = "Open keymap documentation buffer" })
end

return M
