local common = require("modules.theme.sync.common")
local palette = require("modules.theme.palette")

local M = {}

function M.palette_for(item, mode, sync_profile)
  local profile = sync_profile(item)
  if type(profile.delta) == "string" and profile.delta ~= "" then
    return profile.delta
  end
  return mode == "light" and "catppuccin-latte" or "catppuccin-mocha"
end

function M.features_for(delta_palette)
  return table.concat({
    delta_palette,
    "side-by-side",
    "line-numbers",
    "decorations",
  }, " ")
end

local function write_generated_config(theme_key, colors, delta_features)
  local features = delta_features
  if type(features) ~= "string" or features == "" then
    features = theme_key .. " side-by-side line-numbers decorations"
  end

  common.write_lines(vim.fn.expand("~/.dotfiles/Configs/gitconfig/delta-generated.gitconfig"), {
    "# Auto-generated by nvim colorschemes.lua",
    "# Theme key: " .. common.sanitize_key(theme_key),
    "[delta]",
    "\tfeatures = " .. features,
    "\tsyntax-theme = none",
    "\tplus-style = syntax \"" .. colors.ok_bg .. "\"",
    "\tminus-style = syntax \"" .. colors.error_bg .. "\"",
    "\tplus-emph-style = bold syntax \"" .. colors.ok_emph_bg .. "\"",
    "\tminus-emph-style = bold syntax \"" .. colors.error_emph_bg .. "\"",
    "\thunk-header-style = syntax \"" .. colors.selection .. "\"",
    "\thunk-header-decoration-style = \"" .. colors.accent .. "\" box",
    "\tfile-style = bold \"" .. colors.accent .. "\"",
    "\tfile-decoration-style = \"" .. colors.accent .. "\" ul",
    "\tline-numbers-left-style = \"" .. colors.error .. "\"",
    "\tline-numbers-right-style = \"" .. colors.ok .. "\"",
    "\tline-numbers-left-format = \"{nm:>3}│\"",
    "\tline-numbers-right-format = \"{np:>3}│\"",
    "\tline-numbers-plus-style = \"" .. colors.ok .. "\"",
    "\tline-numbers-minus-style = \"" .. colors.error .. "\"",
    "\tline-numbers-zero-style = \"" .. colors.selection .. "\"",
  })
end

function M.sync(theme, ctx)
  local item = ctx.current_theme(theme)
  local mode = ctx.theme_mode(item)
  local colors = palette.build(mode)
  local features = M.features_for(M.palette_for(item, mode, ctx.sync_profile))

  pcall(write_generated_config, item.key, colors, features)
end

return M
