local common = require("modules.theme.sync.common")
local delta = require("modules.theme.sync.delta")
local palette = require("modules.theme.palette")

local M = {}

function M.base_dir()
  local candidates = {
    vim.fn.expand("~/.dotfiles/Configs/lazygit/Library/Application Support/lazygit"),
    vim.fn.expand("~/Library/Application Support/lazygit"),
  }

  for _, dir in ipairs(candidates) do
    if vim.fn.isdirectory(dir) == 1 then return dir end
  end

  return candidates[1]
end

function M.generated_path(theme_key)
  return string.format("%s/config-generated-%s.yml", M.base_dir(), common.sanitize_key(theme_key))
end

local function write_generated_config(path, colors, delta_palette)
  local features = delta_palette
  if type(features) ~= "string" or features == "" then
    features = "catppuccin-mocha"
  end

  local lines = {
    "# Auto-generated by nvim-pure colorschemes.lua",
    "gui:",
    "  theme:",
    "    activeBorderColor:",
    "      - \"" .. colors.border .. "\"",
    "      - bold",
    "    inactiveBorderColor:",
    "      - \"" .. colors.accent .. "\"",
    "    optionsTextColor:",
    "      - \"" .. colors.accent .. "\"",
    "    selectedLineBgColor:",
    "      - \"" .. colors.selection .. "\"",
    "    cherryPickedCommitBgColor:",
    "      - \"" .. colors.selection .. "\"",
    "    cherryPickedCommitFgColor:",
    "      - \"" .. colors.ok .. "\"",
    "    unstagedChangesColor:",
    "      - \"" .. colors.error .. "\"",
    "    defaultFgColor:",
    "      - \"" .. colors.fg .. "\"",
    "    searchingActiveBorderColor:",
    "      - \"" .. colors.warn .. "\"",
    "  authorColors:",
    "    \"*\": \"" .. colors.accent .. "\"",
    "git:",
    "  pagers:",
    "    - pager: delta --paging=never --features=\"" .. delta.features_for(features) .. "\"",
  }

  common.write_lines(path, lines)
end

function M.sync(theme, ctx)
  local item = ctx.current_theme(theme)
  local mode = ctx.theme_mode(item)
  local colors = palette.build(mode)
  local delta_palette = delta.palette_for(item, mode, ctx.sync_profile)

  local generated = M.generated_path(item.key)
  local ok_write = pcall(write_generated_config, generated, colors, delta_palette)
  if ok_write and vim.fn.filereadable(generated) == 1 then
    vim.env.LG_CONFIG_FILE = generated
    return
  end

  local base = M.base_dir()
  local target = (mode == "light") and (base .. "/config-light.yml") or (base .. "/config.yml")
  if vim.fn.filereadable(target) == 1 then
    vim.env.LG_CONFIG_FILE = target
  end
end

return M
