local common = require("modules.theme.sync.common")
local fzf = require("modules.theme.sync.fzf")
local lazygit = require("modules.theme.sync.lazygit")

local M = {}

function M.sync_runtime(theme, ctx)
  local item = ctx.current_theme(theme)
  local mode = ctx.theme_mode(item)
  local theme_key = item.key

  local bat_theme = (mode == "light") and "Catppuccin Latte" or "Catppuccin Mocha"
  local zsh_theme_file = (mode == "light")
      and "$ZSH/custom/themes/catppuccin_latte-zsh-syntax-highlighting.zsh"
      or "$ZSH/custom/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh"

  local lazygit_base = lazygit.base_dir()
  local lazygit_generated = lazygit_base .. "/config-generated-" .. common.sanitize_key(theme_key) .. ".yml"
  local lazygit_fallback = lazygit_base .. ((mode == "light") and "/config-light.yml" or "/config.yml")
  local lazygit_cfg = (vim.fn.filereadable(lazygit_generated) == 1) and lazygit_generated or lazygit_fallback

  local lines = {
    "# Auto-generated by nvim-pure colorschemes.lua",
    "export PURE_THEME_FROM_NVIM=1",
    "export PURE_THEME_AUTHORITY=nvim",
    "export PURE_NVIM_THEME_KEY=\"" .. theme_key .. "\"",
    "export PURE_THEME_MODE=\"" .. mode .. "\"",
    "export BAT_THEME=\"" .. bat_theme .. "\"",
    "export FZF_DEFAULT_OPTS=\"" .. fzf.opts_for_mode(mode) .. "\"",
    "export LG_CONFIG_FILE=\"" .. lazygit_cfg .. "\"",
    "if [[ -n \"$ZSH\" && -f \"" .. zsh_theme_file .. "\" ]]; then",
    "  source \"" .. zsh_theme_file .. "\"",
    "fi",
  }

  pcall(common.write_text_file_if_changed, vim.fn.expand("~/.cache/nvim/theme-sync.zsh"), table.concat(lines, "\n") .. "\n")
end

return M
