# ~/.tmuxinator/petersen.yml
name: petersen
root: ~/workspace/projects/petersen/ar-petersen-cdp
startup_window: backend
startup_pane: 1
on_project_first_start: colima start && docker start oracle-petersen
on_project_stop: docker stop oracle-petersen && colima stop
# enable_pane_titles: "off"
windows:
  - backend:
      layout: main-vertical
      root: ~/workspace/projects/petersen/ar-petersen-cdp/api
      panes: v
  - frontend:
      layout: main-vertical
      root: ~/workspace/projects/petersen/ar-petersen-cdp/web
      panes: v
  - servers:
      root: ~/workspace/projects/petersen
      layout: even-vertical
      panes:
        - backend-server: sh server_run.sh 1 bsf
        - frontend-server: cd ar-petersen-cdp/web && fnm use 14 && yarn && yarn start



